### ISSUE TITLE
Is there any documents for this API?

### ISSUE THREAD

**Issue by dianyong** [timols/java-gitlab-api#114]
Hello,

I am trying to operate a Gitlab server with Java Application, this project is great.
However, I cannot find any documents for the project, anyone can help me?

**Comment by rockwotj** [comment]
I generated some javadocs and put them up on my fork.
https://rockwotj.github.io/java-gitlab-api/

@timols, I can't create a PR for this because there is no gh-pages branch. Could you create this branch? I'll submit a PR so that there is hosted documentation at https://timols.github.io/java-gitlab-api/, and you can add a link in the README

**Comment by timols** [comment]
@rockwotj done!

**Comment by rockwotj** [comment]
@dianyong @songnous @timols 
See https://github.com/timols/java-gitlab-api/pull/124

**Comment by timols** [comment]
See https://timols.github.io/java-gitlab-api/
