### ISSUE TITLE
GitlabAPI#getCommits returns branch commits

### ISSUE THREAD

**Issue by maxim5** [timols/java-gitlab-api#259]
There is an API to [get merge request commits](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-commits), but instead source branch commits are returned, which is not the same.

API version 1.2.8

**Comment by maxim5** [comment]
FYI, I've just found out that the GitLab documentation is wrong:  `/commits` and `/changes` accept merge request **id**, not **iid**. Argh, that's so confusing.

**Comment by Fractaliste** [comment]
I got the same when getting commit from a Tag. It's quiet annoying because it prevents me to get author's name...

**Comment by rkpatel7** [comment]
Since https://github.com/timols/java-gitlab-api/pull/333, it's been possible to [pass in an `apiNameSpace`](https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/GitlabAPI.java#L92-L98) but the default is now [`v4`](https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/GitlabAPI.java#L43).

Regardless, in both v3 and v4, Gitlab provides a way to get commits associated with an MR:
* v3: [`GET /projects/:id/merge_requests/:merge_request_id/commits`](https://gitlab.com/gitlab-org/gitlab-foss/blob/8-16-stable/doc/api/merge_requests.md#get-single-mr-commits)
* v4: [`GET /projects/:id/merge_requests/:merge_request_iid/commits`](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-commits)

Given that it's very similar other than `merge_request_id` vs `merge_request_iid` _and_ all the other methods in this library right now are using `iid`, I think it's safe to update the implementation for [`getCommits`](https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/GitlabAPI.java#L2122-L2138) to use the correct endpoint.

I'll go ahead and submit a PR for this as I have had to implement a workaround for this in the past and would now like to fix it in this library instead of using my workaround. @timols if you have any thoughts/concerns, please let me know.

@Fractaliste I would suggest opening a separate issue for getting commits from a Tag since I would like to keep the scope of this change limited to the original issue.
