### ISSUE TITLE
GitlabApi.findUsers(userName) returns results when calling with empty string

### ISSUE THREAD

**Issue by stefan7jahn** [timols/java-gitlab-api#93]
Hi timols,

when you call the method GitlabApi.findUsers("") with an empty string, it returns strange results. I would expect that there will be returned no user or all users. In my case, we got more than 100 users, but it returns a list of about 10 users..

Best regards,
Stefan

**Comment by timols** [comment]
Hi @stefan7jahn, thanks for letting me know about the issue - would you be interested in submitting a PR for the expected behavior?

**Comment by mpatkisson** [comment]
I think the issue is that if you the argument to the "search" query string parameter is empty, Gitlab, by default returns all users, but paginates the list of users.  As an aside, the "page" and "per_page" query string arguments control which page of data is returned to the user.  The defaults are the first page and a page size of 20 records.  I could be wrong, but am guessing @stefan7jahn saw 20 records and not 10.  

I submitted PR #96 which attempts to address this issue by returning an empty (but non-null) List<GitlabUser> result if the argument to GitlabAPI.findUsers() is null or empty.  I could have gone the other route and returned all users, but IIRC GitlabAPI.getUsers() already does this.  If you would like any changes to this solution, please let me know.
